name: update-tiles

on:
  push:
    paths:
      - "tiles/**/*"
  schedule:
    - cron: "0 4 * * THU"
  workflow_dispatch:

jobs:
  update-tiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: wget https://download.bbbike.org/osm/bbbike/Sydney/Sydney.osm.pbf -O ./tiles/Sydney.osm.pbf
      # https://github.com/systemed/tilemaker/blob/master/docs/RUNNING.md#github-action
      - uses: systemed/tilemaker@v2.3.0
        with:
          # Required, same to --input
          input: ./tiles/Sydney.osm.pbf
          # Required, same to --output. Could be a directory or a .mbtiles files
          output: ./tiles/output
          # Optional, same to --config
          # If not being set, default to resources/config-openmaptiles.config
          config: ./tiles/config.json
          # Optional, same to --process
          # If not being set, default to resources/process-openmaptiles.lua
          process: ./tiles/process.lua
          # Optional, other arguments
          # If not being set, default to '--verbose'
          # extra: --threads 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: cd tiles && npm install
      - run: cd tiles && node ./uploadToR2.js
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
